"""terms

Revision ID: e2cff8544b64
Revises: 8c4bb5c53b7c
Create Date: 2024-06-13 14:10:47.715822

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.types import UUID

# revision identifiers, used by Alembic.
revision: str = "e2cff8544b64"
down_revision: Union[str, None] = "8c4bb5c53b7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "terms_versions",
        sa.Column("id", UUID(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_terms_versions_published_at"),
        "terms_versions",
        ["published_at"],
        unique=False,
    )
    op.create_index(op.f("ix_terms_versions_url"), "terms_versions", ["url"], unique=False)
    op.create_table(
        "terms_version_agreements",
        sa.Column("terms_version_id", UUID(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agreed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["terms_version_id"],
            ["terms_versions.id"],
        ),
        sa.PrimaryKeyConstraint("terms_version_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("terms_version_agreements")
    op.drop_index(op.f("ix_terms_versions_url"), table_name="terms_versions")
    op.drop_index(op.f("ix_terms_versions_published_at"), table_name="terms_versions")
    op.drop_table("terms_versions")
    # ### end Alembic commands ###
